//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodPressureMAUI.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BloodPressureMAUI.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About App.
        /// </summary>
        internal static string AboutAppTitle {
            get {
                return ResourceManager.GetString("AboutAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Data.
        /// </summary>
        internal static string AddDataBtn {
            get {
                return ResourceManager.GetString("AddDataBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sends an SMS whenever new data for blood pressure out of the ranges set below..
        /// </summary>
        internal static string AlertSettingDesc {
            get {
                return ResourceManager.GetString("AlertSettingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Pressure Alarm Values.
        /// </summary>
        internal static string AlertSettingLabel {
            get {
                return ResourceManager.GetString("AlertSettingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Host Name.
        /// </summary>
        internal static string APIHostSetting {
            get {
                return ResourceManager.GetString("APIHostSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location of the REST API..
        /// </summary>
        internal static string APIHostSettingDesc {
            get {
                return ResourceManager.GetString("APIHostSettingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back.
        /// </summary>
        internal static string BackBtn {
            get {
                return ResourceManager.GetString("BackBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not correctly confirm password..
        /// </summary>
        internal static string ConfirmPasswordFailed {
            get {
                return ResourceManager.GetString("ConfirmPasswordFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DataDeleteIconLabel {
            get {
                return ResourceManager.GetString("DataDeleteIconLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string DataEditIconLabel {
            get {
                return ResourceManager.GetString("DataEditIconLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing data.
        /// </summary>
        internal static string DataEditLabel {
            get {
                return ResourceManager.GetString("DataEditLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Editing.
        /// </summary>
        internal static string DataEditTitle {
            get {
                return ResourceManager.GetString("DataEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Entry Failed 🥺.
        /// </summary>
        internal static string DataEntryFailed {
            get {
                return ResourceManager.GetString("DataEntryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add new blood pressure data..
        /// </summary>
        internal static string DataEntryFailedMessage {
            get {
                return ResourceManager.GetString("DataEntryFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new data.
        /// </summary>
        internal static string DataEntryLabel {
            get {
                return ResourceManager.GetString("DataEntryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry for today.
        /// </summary>
        internal static string DataEntryMessage {
            get {
                return ResourceManager.GetString("DataEntryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Entry Success 😃.
        /// </summary>
        internal static string DataEntrySuccess {
            get {
                return ResourceManager.GetString("DataEntrySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New blood pressure data added..
        /// </summary>
        internal static string DataEntrySuccessMessage {
            get {
                return ResourceManager.GetString("DataEntrySuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Entry.
        /// </summary>
        internal static string DataEntryTitle {
            get {
                return ResourceManager.GetString("DataEntryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Not Found 🥺.
        /// </summary>
        internal static string DataNotFound {
            get {
                return ResourceManager.GetString("DataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve data..
        /// </summary>
        internal static string DataNotFoundMessage {
            get {
                return ResourceManager.GetString("DataNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Retrieval Failed 🥺.
        /// </summary>
        internal static string DataViewFailed {
            get {
                return ResourceManager.GetString("DataViewFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve data for viewing..
        /// </summary>
        internal static string DataViewFailedMessage {
            get {
                return ResourceManager.GetString("DataViewFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data View.
        /// </summary>
        internal static string DataViewTitle {
            get {
                return ResourceManager.GetString("DataViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string DateText {
            get {
                return ResourceManager.GetString("DateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only 30 days of data can be viewed at a time..
        /// </summary>
        internal static string DateTotalMax {
            get {
                return ResourceManager.GetString("DateTotalMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Success 😃.
        /// </summary>
        internal static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data was deleted successfully..
        /// </summary>
        internal static string DeleteSuccessMessage {
            get {
                return ResourceManager.GetString("DeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diastolic Blood Pressure.
        /// </summary>
        internal static string DiastolicText {
            get {
                return ResourceManager.GetString("DiastolicText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diastolic:.
        /// </summary>
        internal static string DiastolicTextShort {
            get {
                return ResourceManager.GetString("DiastolicTextShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From:.
        /// </summary>
        internal static string FromDateText {
            get {
                return ResourceManager.GetString("FromDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heart Rate.
        /// </summary>
        internal static string HeartrateText {
            get {
                return ResourceManager.GetString("HeartrateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heart Rate.
        /// </summary>
        internal static string HeartText {
            get {
                return ResourceManager.GetString("HeartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided alarm range for systolic/diastolic blood pressure is invalid..
        /// </summary>
        internal static string InvalidAlarmRange {
            get {
                return ResourceManager.GetString("InvalidAlarmRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password..
        /// </summary>
        internal static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed 🥺.
        /// </summary>
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to log in to account..
        /// </summary>
        internal static string LoginFailedMessage {
            get {
                return ResourceManager.GetString("LoginFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to your account.
        /// </summary>
        internal static string LoginMessage {
            get {
                return ResourceManager.GetString("LoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Success 😃.
        /// </summary>
        internal static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully logged in to account..
        /// </summary>
        internal static string LoginSuccessMessage {
            get {
                return ResourceManager.GetString("LoginSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout Success 😃.
        /// </summary>
        internal static string LogoutSuccess {
            get {
                return ResourceManager.GetString("LogoutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully logged out of account..
        /// </summary>
        internal static string LogoutSuccessMessage {
            get {
                return ResourceManager.GetString("LogoutSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string LogoutTitle {
            get {
                return ResourceManager.GetString("LogoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing field detected..
        /// </summary>
        internal static string MissingField {
            get {
                return ResourceManager.GetString("MissingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OKPrompt {
            get {
                return ResourceManager.GetString("OKPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over.
        /// </summary>
        internal static string OverLabel {
            get {
                return ResourceManager.GetString("OverLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone numbers that will be sent alerts. (Separate new numbers with commas , )..
        /// </summary>
        internal static string PhoneNumberDesc {
            get {
                return ResourceManager.GetString("PhoneNumberDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized Phone Numbers.
        /// </summary>
        internal static string PhoneNumberLabel {
            get {
                return ResourceManager.GetString("PhoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account successfully registered..
        /// </summary>
        internal static string RegistationSuccessMessage {
            get {
                return ResourceManager.GetString("RegistationSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string RegisterBtn {
            get {
                return ResourceManager.GetString("RegisterBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Registration.
        /// </summary>
        internal static string RegisterLabel {
            get {
                return ResourceManager.GetString("RegisterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the information below..
        /// </summary>
        internal static string RegisterMessage {
            get {
                return ResourceManager.GetString("RegisterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Failed 🥺.
        /// </summary>
        internal static string RegistrationFailed {
            get {
                return ResourceManager.GetString("RegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to register account..
        /// </summary>
        internal static string RegistrationFailedMessage {
            get {
                return ResourceManager.GetString("RegistrationFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Success 😃.
        /// </summary>
        internal static string RegistrationSuccess {
            get {
                return ResourceManager.GetString("RegistrationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string RegistrationTitle {
            get {
                return ResourceManager.GetString("RegistrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📅 Reset Date.
        /// </summary>
        internal static string ResetDateBtn {
            get {
                return ResourceManager.GetString("ResetDateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveBtn {
            get {
                return ResourceManager.GetString("SaveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save password.
        /// </summary>
        internal static string SavePassword {
            get {
                return ResourceManager.GetString("SavePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔍 Search.
        /// </summary>
        internal static string SearchBtn {
            get {
                return ResourceManager.GetString("SearchBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Not Saved 🥺.
        /// </summary>
        internal static string SettingsNotSaved {
            get {
                return ResourceManager.GetString("SettingsNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Saved 😃.
        /// </summary>
        internal static string SettingsSaved {
            get {
                return ResourceManager.GetString("SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your settings were saved successfully..
        /// </summary>
        internal static string SettingsSavedMessage {
            get {
                return ResourceManager.GetString("SettingsSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string SignInBtn {
            get {
                return ResourceManager.GetString("SignInBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert!!! for {0}.
        /// </summary>
        internal static string SMSMessage {
            get {
                return ResourceManager.GetString("SMSMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diastolic value = {0} (Range {1} - {2})..
        /// </summary>
        internal static string SMSMessageDiastolic {
            get {
                return ResourceManager.GetString("SMSMessageDiastolic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Systolic value = {0} (Range {1} - {2})..
        /// </summary>
        internal static string SMSMessageSystolic {
            get {
                return ResourceManager.GetString("SMSMessageSystolic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Systolic Blood Pressure.
        /// </summary>
        internal static string SystolicText {
            get {
                return ResourceManager.GetString("SystolicText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Systolic:.
        /// </summary>
        internal static string SystolicTextShort {
            get {
                return ResourceManager.GetString("SystolicTextShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string TimeText {
            get {
                return ResourceManager.GetString("TimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To:.
        /// </summary>
        internal static string ToDateText {
            get {
                return ResourceManager.GetString("ToDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under.
        /// </summary>
        internal static string UnderLabel {
            get {
                return ResourceManager.GetString("UnderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Data.
        /// </summary>
        internal static string UpdateDataBtn {
            get {
                return ResourceManager.GetString("UpdateDataBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Failed 🥺.
        /// </summary>
        internal static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update blood pressure data..
        /// </summary>
        internal static string UpdateFailedMessage {
            get {
                return ResourceManager.GetString("UpdateFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Success 😃.
        /// </summary>
        internal static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood pressure data was updated successfully..
        /// </summary>
        internal static string UpdateSuccessMessage {
            get {
                return ResourceManager.GetString("UpdateSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string UsernamePlaceholder {
            get {
                return ResourceManager.GetString("UsernamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
